### ISSUE TITLE
BUG - multiple formula references breaks refactor

### ISSUE THREAD

**Issue by djbelknapdbs** [fivetran/dbt_salesforce_formula_utils#13]
**Are you a current Fivetran customer?** 
Yes

**Describe the bug**
When a formula references more than one earlier formula, the refactor macro creates more than one formula in the output array which breaks the pivot macro.

Here's an example. This is the data in the fivetran_formula table:
|field|sql|
|---|---|
|field1|null|
|field2|null|
|field3|CASE field1 = 'abc' OR field2 = 'abc' WHEN true THEN 'value1' ELSE 'value2' END|

This creates the following structure for the key_val variable returned to the pivot macro:
```
[
  ['field1','null_value'],
  ['field2','null_value'],
  ['field3', "case field1 = 'abc' or (null) = 'abc' WHEN true THEN 'value1' ELSE 'value2' END", "CASE (null) = 'abc' OR field2 = 'abc' WHEN true THEN 'value1' ELSE 'value2' END"]
]
```
Notice field3 has two values where field1 and field2 got replaced separately.

**Expected behavior**
There should be a single formula with all earlier formulas refactored out.
```
[
  ['field1','null_value'],
  ['field2','null_value'],
  ['field3', "case (null) = 'abc' or (null) = 'abc' WHEN true THEN 'value1' ELSE 'value2' END"]
]
```

**Package Version**

```yml
  - package: fivetran/salesforce_formula_utils
    version: [">=0.1.0", "<0.2.0"]
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Please indicate the level of urgency** 
Low - came up while I was working on follow-up to #6 .

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [x] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for opening this issue @djbelknapdbs. This package is currently undergoing a lot of feature enhancements and I will take this one into consideration as you would want the result of the macro to be able to identifier more than one formula if that is the case. 

I will keep you updated here when we release `v0.2.0` of this package which will contain the bug fix for this issue.

Thanks again for all your contributions to this package 😄

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for calling this out @djbelknapdbs! I have just cut `v0.2.0` release of this package and should be live within the hour. This bug has been addressed.

Please let me know if you notice any other issues when exploring this package.
