### ISSUE TITLE
BUG - From Clause with Redshift Results in Error

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_salesforce_formula_utils#36]
**Are you a current Fivetran customer?** 

Fivetran created Issue

**Describe the bug**

The package cannot create all SQL script, it tries to put schema name in front of the table names but it can’t put properly.
( select main_table.id, ( user__alias.email ) as email_c from "prod"."salesforce".""opportunity left join "prod"."salesforce".""quote_c as quote_c__alias on main_table.primary_quote_c = quote_c__alias.id left join "prod"."salesforce".""user as user__alias on quote_c.signer_c = user__alias.id ) as view_sql_1 
When you run the above query on Redshift, it does not like the appended prod.

**Steps to reproduce**
1. Use Redshift
2. Run the macro
3. See the failure

**Expected behavior**

Running this macro on Redshift does not result in an error.

**Warehouse**

 
- [ ] BigQuery
- [X] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**

**Comment by fivetran-joemarkiewicz** [comment]
I believe a similar conditional for Redshift will need to be applied in the below lines.

https://github.com/fivetran/dbt_salesforce_formula_utils/blob/55b800591c04e81329bfcb731e0d70b3f6d31e89/macros/sfdc_formula_view_sql.sql#L13-L21

**Comment by fivetran-jamie** [comment]
yeah adding a redshift conditional there fixed the original error, but now i'm seeing some trouble around `as main table`

```sql
, ( select main_table.id, ( cast( opportunity__alias.stage_name as string ) = '6 - won' ) as related_renewal_opp_closed_won_c from "redshift-test"."salesforce".opportunity as main_table left join "redshift-test"."salesforce".opportunity as main_table as opportunity__alias on main_table.related_renewal_opportunity_c = opportunity__alias.id ) as view_sql_20
```

the join_to_table (opportunity) joins on itself with an alias, and that already-aliased table is having `as main_table` added to it as well, throwing an error (and also if it did't already have the alias, this would be an issue of both sides of the join having the same name, `main_table`)... racking my brain rn for how to isolate the pre-`from` instance of the `opportunity` as the only place we should be adding `as main_table`.... 🤔

**Comment by fivetran-joemarkiewicz** [comment]
Great call out!

This is actually something we have come across before and the connector team is planning to handle all `main_table` and other aliasing. We will actually be removing the alias and `main_table` logic shortly. Actually most likely will want to do this today haha. I have a [draft PR](https://github.com/fivetran/dbt_salesforce_formula_utils/pull/38) open that removes the functionality. Would you be able to review this when you have a moment?

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for implementing this @fivetran-jamie! This is now live in the latest release of the dbt package! 🎉
