### ISSUE TITLE
Error in run of macro: sfdc_formula_view

### ISSUE THREAD

**Issue by RivkiHofman** [fivetran/dbt_salesforce_formula_utils#39]
Hi

My dbt version is: 0.21.0 .
I want to use with macro: sfdc_formula_view
I installed the packages, the packages.yml is seems so:

packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.6.0", "<0.8.0"]

  - package: fivetran/fivetran_utils
    version: [">=0.2.0", "<0.3.0"]

  - package: fivetran/salesforce_formula_utils
    version: [">=0.5.0", "<0.6.0"]

Then. I created a model for example: opportunity_formula.sql 
In this model there is a code:
{{ salesforce_formula_utils.sfdc_formula_view(source_table='opportunity') }}

I tried to run it by dbt run and failed on problem in code, in the line that create the : view_sql_2, this line start with:
( select main_table.id, ( case top_division_c = 'enterprise' when true then case...
The field top_division_c exists in opportunity and also in account, so needed to add the alias table: main_table.top_division_c .

Also when I run on account table, there are many problems, for example, there are tables that in salesforce look like with 2__, and in fivetran with 1_: the table TERRITORY_MASTER_TABLE__C, in fivetran database looks like : TERRITORY_MASTER_TABLE_C(1 _ before the C), or an additional example, in the line that create the table: view_sql_12 there is 2 alias for 1 table:
left join FIVETRAN_DATABASE.NICE_SALESFORCE.account as main_table as account__alias

So, I want to understand maybe I use with incorrect version.
Can you guide me please how can I use it?
I did all according by your documentation, but it's still wrong.

Thanks for your response asap.
Rivki

**Comment by fivetran-joemarkiewicz** [comment]
Hi @RivkiHofman thanks so much for opening this issue!

Looking at your versioning and config, it looks to all be correct. We are currently aware of this `main_table` aliasing issue and we are currently working on implementing a fix. I imagine once we are able to resolve this issue then your error should fix itself out. 

I will post back here once we have the fix we are working on implemented.

**Comment by RivkiHofman** [comment]
Hi,
Thank a lot for your answer.
The problem with alias for main table is small problem, please pay attention to what I wrote about the account table,(tables with 2 aliases and names of tables like as salesforce and not like as fivetran), I think that those problems are bigger.

I would appreciate your update.

**Comment by fivetran-joemarkiewicz** [comment]
Hey @RivkiHofman 

I completely agree that the points you made regarding the account table are bigger issues. The double alias should be resolved once we move the aliasing to the connector (should be sometime this week). I am a bit curious about the tables having different names. Are you saying the `fivetran_formula` table is trying to reference a table with 1 underscore, but the actual table in the warehouse and Salesforce has 2 underscores?

**Comment by fivetran-joemarkiewicz** [comment]
Hi @RivkiHofman that is very interesting. Let me look further into this and see what is happening with this renaming.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @RivkiHofman thanks for providing more detail!

> Calculate for fields: cea_sales_territory_c, parent_ci_mapping_c
In the 2 tmp tables: view_sql_1 & view_sql_2 there are 2 alias for account table:
FIVETRAN_DATABASE.NICE_SALESFORCE.account as main_table as main__table
- Which version of the package are you currently using? I believe if you use the latest version of the package then this double aliasing should be resolved.

> Calculate for field: region_c
> In the end of the line there is a code: else account_region_c from account table, there is no such field in this table, maybe it means to account.region_c (the field region_c from account table) or other something...
-  Is  `account_region_c` possible a formula field within the account table? That may explain why it is looking for a field that technically doesn't exist yet.?

> Calculate for field: ma_name_c
> main__table.account_known_as_c & main__table.billing_country_c but there is no table with alias main__table.
> top_parent_account__r.name but there is no select from table top_parent_account__r.
> account_known_as__c with 2 underscore, but in fivetran database with 1 underscore.
- The `main_table` issues I believe should be resolved in the latest version of the package. However, I am still looking into how we can resolve the double and singe underscoring issue you have raised here.

On a final note, would you be open to sharing the `sql` or `view_sql` that is used in the formulas you are trying to use here? That would help me investigate closer what could be going wrong. Thanks!

**Comment by RivkiHofman** [comment]
1. 
This is my packages.yml:
packages:

package: dbt-labs/dbt_utils
version: [">=0.6.0", "<0.8.0"]

package: fivetran/fivetran_utils
version: [">=0.2.0", "<0.3.0"]

package: fivetran/salesforce_formula_utils
version: [">=0.5.0", "<0.6.0"]

I can't use with the last version because my dbt version is: 0.21.0 .

2. My formula field is: region_c, in the account table there is no field: account_region_c, seems from sql that I get from dbt, that 
this calculate within the account table, but the code try to use with  a wrong field.

Will it not be possible to correct the double alias in this version?

I try to attached the sql, I hope you can see it, if not, I can send you the file with sql by mail.

[account_formula.txt](https://github.com/fivetran/dbt_salesforce_formula_utils/files/7890606/account_formula.txt)

Thanks.

**Comment by RivkiHofman** [comment]
The code is very long, so I focus where my issues:

1. lines:  349,362 (cea_sales_territory_c, parent_ci_mapping_c)
2. line: 328 (region_c)
3. line: 332 (ma_name_c)

**Comment by fivetran-joemarkiewicz** [comment]
Hi @RivkiHofman thanks for all of this additional information.

I have been able to connect with our engineering team and they have determined it is most likely an issue that needs to be addressed within the connector. Specifically how the connector syncs data into the `fivetran_formula` table in order to rectify the naming changes.

Would you be able to create a [Fivetran Support](https://support.fivetran.com/hc/en-us/requests/new) question on this matter and link this github ticket if possible? I will then escalate internally so this can be seen by the team. Thank you!

**Comment by RivkiHofman** [comment]
Thanks @fivetran-joemarkiewicz 

I created a request: https://support.fivetran.com/hc/en-us/requests/53432 and put there the link of this issue.

**Comment by RivkiHofman** [comment]
Hi @fivetran-joemarkiewicz 

Is there anything new about this issue?
Do you have time estimation when we will be able to use this package?

Thanks.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @RivkiHofman the engineering team is currently working on a fix and we will let you know here and in the support ticket once the fix is live. 

In the meantime, I will check in to see what an estimated time of completion may be.

**Comment by RivkiHofman** [comment]
Hi @fivetran-joemarkiewicz 

The ticket is in handling, thanks for that.
What about the problem with 2 aliases? can you add the fix of it to version: 
  package: fivetran/salesforce_formula_utils
  version: [">=0.5.0", "<0.6.0"]
Or match the last version to our dbt version :  0.21.0 ?

Thanks.

**Comment by fivetran-joemarkiewicz** [comment]
The aliasing of the formula field joins should be properly handled within the latest release of the package! As such, I will close this issue. Please feel free to re-open if needed. Thank you!
