### ISSUE TITLE
BUG - Reserved words handling for fields_to_include bugfix

### ISSUE THREAD

**Issue by fivetran-sheringuyen** [fivetran/dbt_salesforce_formula_utils#45]
**Are you a current Fivetran customer?** 

Fivetran created

**Describe the bug**

Posted on dbt/tools-fivetran slack. The new `fields_to_include` update (0.6.2) is working as expected, however, Salesforce has a table named "case" therefore it creates an issue when referring to the "case" table as an alias within a `CASE WHEN` statement. We should add an update to handle reserved words.

**Package Version**

```yml
copy packages.yml here
```
packages:
  - package: fivetran/salesforce_formula_utils
    version: 0.6.2

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake (Customer specified issue happening in Snowflake, but could very well be happening in other DBs as well)
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Comment by fivetran-joemarkiewicz** [comment]
For context, the dbt Slack conversation and detail of the issue can be seen [here](https://getdbt.slack.com/archives/C01D1R2JLLA/p1645541527453169).

Further, another customer mentioned a similar issue on dbt Slack in this [thread](https://getdbt.slack.com/archives/C01D1R2JLLA/p1646193624756599?thread_ts=1646190769.524459&cid=C01D1R2JLLA).

**Comment by rob-seaberg** [comment]
Are you a current Fivetran customer?

yes

Describe the bug

I am experiencing the same [issue ](https://github.com/fivetran/dbt_salesforce_formula_utils/issues/45#issue-1147316716) when using `sfdc_formula_view` for with the salesforce case table.  I see that only Snowflake is checked above so I want to flag that it is a BQ issue as well
  
Package Version

    package: fivetran/salesforce_formula_utils
    version: 0.6.4

Warehouse

BigQuery

**Comment by fivetran-joemarkiewicz** [comment]
Hi all, 

The `using_quoted_identifiers=true` argument to the macro which was introduced within the [v0.7.2](https://github.com/fivetran/dbt_salesforce_formula_utils/releases/tag/v0.7.2) release of the package should address the reserved word issue raised within this bug report.

As such, I will close this issue and mark as resolved. Please feel free to reopen if the issue still persists.
