### ISSUE TITLE
[Bug] CreatedBy Salesforce function is not dealt with properly

### ISSUE THREAD

**Issue by moreaupascal56** [fivetran/dbt_salesforce_formula_utils#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I have a formula on opportunity table  like : 
```
IF(
AND(
    CreatedBy.Id <>  OwnerId,  
IF(
    NOT(CONTAINS(Owner.UserRole.Name,"some_string")),
    ),
IF(
    NOT(CONTAINS(Owner.UserRole.Name,"some_other_string")),
    )    
    ),True,False) 
```

(It is more complicated in reality but anyway this is the problematic part) 

So we should have 3 joins : 
- 1 for the `CreatedBy.id ` which should be : `left join user on user.id = opportunity.created_by_id
`
- 2 to catch user_role : 
```
 left join user on user.id = opportunity.owner_id
 left join user_role on user.user_role_id = user_role.id
```

The first one is not rendered by the tool and `CreatedBy.Id
` is translated to `user__alias.id
` so `opportunity.created_by_id` because of the join, which is giving 0 lines in return because of the `CreatedBy.Id <>  OwnerId`  line. 

It seems that the tool is not really understanding the `CreatedBy.Id`part or I am missing something. 

### Relevant error log or model output

Content of fivetran_formula : 
table : opportunity

SF formula:
```

IF(
AND(
    CreatedBy.Id <>  OwnerId,
IF(
    NOT(CONTAINS(Owner.UserRole.Name,"some-string")),
    ),
IF(
    NOT(CONTAINS(Owner.UserRole.Name,"some-string2")),
    )    
    ),True,False)
```

view_sql: 

```
select 
main__table.id, 
( 
CASE  
  user__alias.id <> main__table.owner_id 
  AND 
  CASE 
    WHEN NOT REGEXP_INSTR( user_role__alias.name, 'some-string' ) > 0  
    ELSE  NOT REGEXP_INSTR( main__table.closer_role_c, 'some-string' ) > 0  
    END 
  AND 
  CASE 
    WHEN  NOT REGEXP_INSTR( user_role__alias.name, 'some-string2' ) > 0  
    ELSE  NOT REGEXP_INSTR( main__table.closer_role_c, 'some-string2' ) > 0  
    END 
WHEN true THEN True ELSE False END ) 
as value_we_want 
from opportunity as main__table 
left join user as user__alias on main__table.owner_id = user__alias.id 
left join user_role as user_role__alias on user__alias.user_role_id = user_role__alias.id
```

### Expected behavior

we should have : 

view_sql: 

```
select 
main__table.id, 
( 
CASE  
  user__alias_NEW.id <> main__table.owner_id 
  AND 
  CASE 
    WHEN NOT REGEXP_INSTR( user_role__alias.name, 'some-string' ) > 0  
    ELSE  NOT REGEXP_INSTR( main__table.closer_role_c, 'some-string' ) > 0  
    END 
  AND 
  CASE 
    WHEN  NOT REGEXP_INSTR( user_role__alias.name, 'some-string2' ) > 0  
    ELSE  NOT REGEXP_INSTR( main__table.closer_role_c, 'some-string2' ) > 0  
    END 
WHEN true THEN True ELSE False END ) 
as value_we_want 
from opportunity as main__table 
**left join user as user__alias_NEW on main__table.created_by_id = user__alias_NEW.id**  
left join user as user__alias on main__table.owner_id = user__alias.id 
left join user_role as user_role__alias on user__alias.user_role_id = user_role__alias.id
```

### dbt Project configurations

--

### Package versions

0.6.4

### What database are you using dbt with?

snowflake

### dbt Version

--

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @moreaupascal56 thanks so much for opening this issue!

Unfortunately, this is one that will need to be addressed within the connector itself (which my team does not have much insight into). I would recommend opening a [Support Ticket](https://support.fivetran.com/hc/en-us) so one of our engineers may look at this deeper and be able to address the bug within the connector.

**Comment by moreaupascal56** [comment]
Hey 👋  Ok yes I understand, so everything that is already in the Formula table is done by the connector that's logical. 
Thanks for your answer and have a great day 🌞
