### ISSUE TITLE
[Feature] Allow users to select materialization type in salesforce_formula_view

### ISSUE THREAD

**Issue by abdullahhfz** [fivetran/dbt_salesforce_formula_utils#53]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

salesforce_formula_utils.salesforce_formula_view.sql hardcodes the materialization. As a user I am unable to change that, even if I set a configuration in the dbt_project.yml or create a config in the model sql file using CTE. The only way I can change the materialization is by changing the salesforce_formula_view.sql file and hard coding it to materialize as a table. This is problematic as I need to use these updated formula tables for downstream models. 

There should be an argument that allows the user to change the materialization configuration of a model. 

### Describe alternatives you've considered

I have tried changing the config in the dbt_project.yml. Also, tried changing the config in the model sql file above the macro. I have also created a CTE using the macro and then overriding the config in the model sql file. None of these solutions work. Only hardcoding the salesforce_formula_view.sql file. 

### Are you interested in contributing this feature?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Closed this issue as the feature has been implemented in the latest version of the package.
