### ISSUE TITLE
[Bug] differing_order_account_c throws Unknown Alias error in Snowflake

### ISSUE THREAD

**Issue by BIBenHBP** [fivetran/dbt_salesforce_formula_utils#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When Dbt tries to run the Transaction table from salesforce into snowflake it fails and throws an unkown alias error on order_c__alias.account_c. In researching the compiled sql it looks like the order of the Left Outer joins is causing this. Reordering the join clause fixes the issue.
![image](https://user-images.githubusercontent.com/102375216/187530642-72dadf6f-3e6b-4764-896e-adb46894e38a.png)

```
select ---Doesn't work
*
from fivetran.cl_salesforce.transaction_c as main__table 
left outer join fivetran.cl_salesforce.account as account__alias on order_c__alias.account_c = account__alias.id                 
left outer join fivetran.cl_salesforce.order_c order_b__alias on order_line_item_c__alias.order_c = order_b__alias.id  
left outer join fivetran.cl_salesforce.order_line_item_c as order_line_item_c__alias on main__table.order_line_item_c = order_line_item_c__alias.id 
;             
                
                
                
select --works
  *
from fivetran.cl_salesforce.transaction_c as main__table ---This works becaue the tables are correctly ordered
left outer join fivetran.cl_salesforce.order_line_item_c as order_line_item_c__alias on main__table.order_line_item_c = order_line_item_c__alias.id 
left outer join fivetran.cl_salesforce.order_c order_c__alias on order_line_item_c__alias.order_c = order_c__alias.id                 
left outer join fivetran.cl_salesforce.account as account__alias on order_c__alias.account_c = account__alias.id 

;
        
```        

### Expected behavior

Model runs and adjusts the formulas for the field as needed

### dbt Project configurations

vars:
  sfdc_exclude_formulas: ('sgmt_parent_total_score_c','fferpcore_is_shipping_address_validated_c','fferpcore_is_billing_address_validated_c','revenue_milestones_approved_c','days_since_stage_update_c','region_c','differing_order_account_c')

### Package versions

packages:
  - package: fivetran/salesforce_formula_utils
    version: [">=0.6.0", "<0.7.0"]

### What database are you using dbt with?

snowflake

### dbt Version

1.0

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @BIBenHBP thanks so much for opening this issue!

We actually just released an update to the package (and the connector) that may address this issue for you! Would you be able to upgrade your package to the latest version `0.7.0` and try our [option #1](https://github.com/fivetran/dbt_salesforce_formula_utils#option-1-generate-all-relevant-formula-fields-at-once) in the README. The only adjustment you will need to make is ensuring you include the `fivetran_formula_model` table in your source.yml file for Salesforce.

Let me know if these changes address your error!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @BIBenHBP upgrading the package to the latest version and using Option #1 linked above should do the trick with solving this issue. 

I am going to close this issue as I believe this upgrade path should solve the original bug identified. Please feel free to re-open the issue if this does not address your initial bug report. Thanks!
