### ISSUE TITLE
SQL Can't Handel Null

### ISSUE THREAD

**Issue by jmcdonald-moveworks** [fivetran/dbt_salesforce_formula_utils#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

For fields involving numeric values the translation from Salesforce formula to SQL isn't exactly correct. 

I have a salesforce field named [Growth ARR] with the following salesforce formula: \
`ARR__c - Renewal_Baseline_ARR__c
`

This package translates this simple formula to:
`arr_c - renewal_baseline_arr_c
`

Salesforce formulas have some sort of if null handling that allows 100k - null to be equal to 100k. In SQL 100k - null = null, which doesn't match salesforce. It would be better for the formula translation to include a coalesce. Here is my "correct" translation: 
`coalesce(arr_c, 0) - coalesce(renewal_baseline_arr_c, 0)`

### Expected behavior

numeric value - null = numeric value

### dbt Project configurations

name: "gtm_analytics"

config-version: 2
version: 1.1.0

### Package versions

packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.4
  - package: fivetran/salesforce_formula_utils
    version: 0.7.0

### What database are you using dbt with?

snowflake

### dbt Version

1.1.1

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @jmcdonald-moveworks thanks so much for opening this issue. This is definitely an interesting scenario. So if I am understanding this correctly, Salesforce interprets a certain number of null records as non null?

**Comment by jmcdonald-moveworks** [comment]
@fivetran-joemarkiewicz I believe that's correct. Behind the scenes it seems to have some sort of null handling that replaces null with 0: 
<img width="1513" alt="sfdc" src="https://user-images.githubusercontent.com/104589818/188726197-cff7bb7b-36d3-4a2d-b25c-87deaa5cf2b0.png">

**Comment by fivetran-joemarkiewicz** [comment]
As opening a support ticket (linked in my previous response) is most likely the path forward to resolution, I will close this bug report.

Please feel free to reopen if you believe there is more to discuss.
