### ISSUE TITLE
invalid input syntax for type boolean: ""

### ISSUE THREAD

**Issue by mjinu007** [fivetran/dbt_salesforce_formula_utils#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Hello,

We have already gone through this issue with Joe at Fivetran support.

We have the latest fivetran salesforce formula package,

packages:
  - package: fivetran/salesforce_formula_utils
    version: [">=0.7.0", "<0.8.0"]

When we run the following macro for lead object,

{{ salesforce_formula_utils.sfdc_formula_view(source_table='lead',full_statement_version=true)}}, we get the boolean error.

### Relevant error log or model output

```shell
Server error: Database Error in rpc request (from remote system)
invalid input syntax for type boolean: ""
```

### Expected behavior

SF Lead table with all the formula fields

### dbt Project configurations

sources:
  - name: salesforce

    tables:

      - name: contact

      - name: opportunity

      - name: account

      - name: lead

      - name: account_history

      - name: user

      - name: campaign

      - name: campaign_member

      - name: partner_program_c

      - name: fivetran_formula
      
        description: A table containing a mapping of sfdc formulas with a reference to corresponding table objects for the formulas to be applied.
        columns:
          - name: field
            description: Name of the formula
          - name: object
            description: Reference to the table the formula is to be applied
          - name: formula
            description: Salesforce defined formula
          - name: sql
            description: Standard sql interpretation of the Salesforce defined formula, generated by Fivetran
          - name: _fivetran_synced
            description: Timestamp of when the record was synced by Fivetran
            
      - name: task

      - name: event

      - name: fivetran_formula_model

### Package versions

packages:
  - package: fivetran/salesforce_formula_utils
    version: [">=0.7.0", "<0.8.0"]

### What database are you using dbt with?

redshift

### dbt Version

1.0

### Additional Context

Let me know if you need more info

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @mjinu007 thanks so much for opening this issue and for meeting with me earlier in the day.

I have been able to look into the issue we encountered on our call where the `lead` table was pulling in the code for the `opportunity` object. I was able to discover the issue at hand and have a fix implemented in a working branch and subsequent PR linked above. I should have this included in the next release by tomorrow morning.

Once this is live, it should resolve the lead model we were troubleshooting. For the more apparent error below:
```sh
Server error: Database Error in rpc request (from remote system)
invalid input syntax for type boolean: ""
```

This looks to be a translation error, and one we will want to address within the connector. For this error, would you be able to open a [Support Ticket](https://support.fivetran.com/hc/en-us) so our engineering team may investigate and address further.

**Comment by fivetran-joemarkiewicz** [comment]
@mjinu007 I just wanted to get back and let you know the change I mentioned above is now live in the latest release of the dbt package!

For the translation error, I would recommend opening the support ticket for our engineering team to resolve. As the issue on the dbt package side has been addressed, I will close out this ticket.
