### ISSUE TITLE
[Feature] Updgrade fivetran_utils to 0.4.0

### ISSUE THREAD

**Issue by rossserven** [fivetran/dbt_salesforce_formula_utils#63]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Running into dependency issues trying to upgrade dbt_utils to 0.9.X.  Recently fivetran_utils 0.4.0 moved to 0.9.X+.  If dbt_salesforce_formula_utils can move to fivetran_utils we can upgrade.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @rossserven thanks for opening this feature request! We are actually in the process of upgrading all of our Fivetran dbt packages to be compatible with the latest fivetran-utils and dbt-utils. These updates _should_ be live at the end of this month. 

I will post back with more details as we continue to work on this effort.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @rossserven thanks again for opening this feature request! This package has since been upgrading to the latest version of fivetran_utils in the most recent release! As such, you will be able to upgrade and see the latest version of fivetran_utils being used.
