### ISSUE TITLE
BUG - Detail roll-up formulas break subsequent formulas

### ISSUE THREAD

**Issue by djbelknapdbs** [fivetran/dbt_salesforce_formula_utils#7]
**Are you a current Fivetran customer?** 
Yes

**Describe the bug**
I have two objects with a master-detail relationship with the Account object. The account object has roll-up formulas from the detail records, and formulas based on those roll-up fields. The roll-up formulas are excluded so the fields don't get created, but then the subsequent formulas fail because the roll-up field wasn't created.

**Steps to reproduce**
1. Create a master-detail relationship from Account (master) to another object (detail) in Salesforce
2. On the master object, create a roll-up formula from the detail object
3. Create another formula based on the roll-up created in step 2
4. Sync and check the formula table
  a. The formula from step 2 will be left out (appropriate since it's a relationship)
  b. The formula in step 3 will be intact

**Expected behavior**
Two options - create the roll-up field and set it to null, or don't create either field. The latter is probably preferable.

**Package Version**

```yml
  - package: fivetran/salesforce_formula_utils
    version: [">=0.1.0", "<0.2.0"]
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Please indicate the level of urgency** 
Medium - it's keeping us from switching to Fivetran for production runs.

**Are you interested in contributing to this package?** 

- [x] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

Depending on the solution you want to implement, this might be better solved in the connector than in dbt.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @djbelknapdbs thanks for opening this issue and for your detailed description of the issue!

We have encountered another customer who experienced a similar issue with the roll-up fields you described and are working on a solution. You mentioned your preferred solution would be to remove the roll-up fields? Would you try and recreate them again in downstream models, or do you feel there no need at all to include them?

**Comment by djbelknapdbs** [comment]
Hi @fivetran-joemarkiewicz - Thanks for the update. If you can get them included with real logic that would be ideal! But since they are a reference to other objects I figured it wouldn't be in scope for this package unless lookups get added.

**Comment by fivetran-joemarkiewicz** [comment]
I completely agree. I will most likely scope this work out for our next sprint to remove the roll-up fields, but will continue the conversation with our internal team for having the real logic be built out in the future.

**Comment by fivetran-joemarkiewicz** [comment]
@djbelknapdbs I have been able to add logic to the most recent merge to `main` which will carry the null value from these roll-up fields through to other formula fields which reference these. This way, since the current roll-up field is null then the formula field that references this roll-up field will also be null now. This should be fix the error message you were receiving previously on this issue. 

While this doesn't fix doesn't bring the true roll-up field sql into the table, I do think it would be helpful if you were able to create a [Support Ticket](https://support.fivetran.com/hc/en-us) asking for this feature if you already have not done so. I believe this is being discussed, but it will help you gain visibility for when/if this feature is added in the future.

**Comment by fivetran-joemarkiewicz** [comment]
Closing this ticket as next steps most likely have been migrated to a support ticket. Additionally, if you still need to remove the rollup fields you can use the variable `sfdc_exclude_formulas` to exclude certain fields.

Please feel free to reopen this issue or open a new one if you feel this has not been addressed or come across any other issues.
