### ISSUE TITLE
[Bug] Join of two tables does not respect Fivetran history mode 

### ISSUE THREAD

**Issue by icemtel** [fivetran/dbt_salesforce_formula_utils#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I am using Fivetran in History mode (which enables SCD2 on source tables).

On Task object in salesforce, I have a formula, that basically looks up a field on the task owner: `Owner:User.SomeFieldName__c`. 

In this case, `salesforce_formula_utils.sfdc_formula_view` compiles into a join of `salesforce.task` and `salesforce.user`. Because both of the tables are in history mode, `user.id` is not unique and join produces a huge table, much larger than the original `salesforce.task`.

Here's the dbt model code I'm using:
```
{{ salesforce_formula_utils.sfdc_formula_view(
    source_table='task',
    full_statement_version=true) 
}}
```

Which gets compiled into:
```
SELECT mt.id,
           mt._fivetran_start,mt._fivetran_end,mt._fivetran_active,
           jt1.some_field_name_c AS xyz,
FROM salesforce.task AS mt
LEFT JOIN salesforce.user AS jt1 ON mt.owner_id=jt1.id 
```

Note: I removed irrelevant columns and formatted for readability.

### Expected behavior

When we join to get extra information, it should never change number of rows.
 
If the package does not support history mode, this should be clearly labelled. 
If you want to support history mode as well, then you may need to decide whether to join rows from the past with rows from the past, or with the active ones.

### dbt Project configurations

I believe the problem does not depend on my configurations.

### Package versions

```
dbt deps
08:32:52  Running with dbt=1.5.0
08:32:55  Installing dbt-labs/codegen
08:32:55  Installed from version 0.10.0
08:32:55  Up to date!
08:32:55  Installing calogica/dbt_date
08:32:56  Installed from version 0.7.2
08:32:56  Up to date!
08:32:56  Installing fivetran/salesforce_formula_utils
08:32:56  Installed from version 0.9.0
08:32:56  Up to date!
08:32:56  Installing dbt-labs/dbt_utils
08:32:57  Installed from version 1.1.1
08:32:57  Up to date!
08:32:57  Installing fivetran/fivetran_utils
08:32:57  Installed from version 0.4.7
08:32:57  Up to date!
```

### What database are you using dbt with?

bigquery

### dbt Version

1.5.0

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by icemtel** [comment]
On the other hand, running with `full_statement_version=false` produces the expected behavior (there's no join in the compiled code).

**Comment by icemtel** [comment]
@fivetran-joemarkiewicz  done ✅

**Comment by fivetran-joemarkiewicz** [comment]
Great! I will close this issue as the support ticket was the way to go!

**Comment by icemtel** [comment]
In case anyone stumbles into this - Fivetran support has fixed this - only `_fivetran_active` rows are be joined.
