### ISSUE TITLE
[Bug] Some fields not being calculated due to incorrect dependency error

### ISSUE THREAD

**Issue by RichardThRivera** [fivetran/dbt_salesforce_formula_utils#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Certain fields from SFDC are not being calculated using formulas by incorrectly stating dependent fields are not being synced.

For example, from object SBQQ_Quote_c: 

- Calculation for UZ_CalculatedSubscriptionTerm__c, dependent field is SBQQ__StartDate__c

![image](https://github.com/fivetran/dbt_salesforce_formula_utils/assets/79607656/d295a9f4-ff33-4816-b0e8-9ae677045402)

- Field is being captured via Fivetran

![image](https://github.com/fivetran/dbt_salesforce_formula_utils/assets/79607656/6f39a65b-bcd8-4668-ac8b-93124c339bc7)

- Field name is being changed by the connector to sbqq_start_date_c

![image](https://github.com/fivetran/dbt_salesforce_formula_utils/assets/79607656/85e5ba51-c7bb-40ca-ac33-5aeb798346b9)

### Expected behavior

If fivetran connector is changing the name of the field, the formula should change the name in the same manner to perform the calculation

### dbt Project configurations

n/a

### Package versions

packages:  
  - package: dbt-labs/audit_helper
    version: [">=0.8.0", "<0.10.0"]

  - package: dbt-labs/codegen
    version: 0.9.0

  ##- package: elementary-data/elementary
    ##version: 0.7.8
    ## Docs: https://docs.elementary-data.com

  - package: entechlog/dbt_snow_mask
    version: 0.2.4

  - package: fivetran/greenhouse
    version: 0.6.0

  - package: fivetran/zendesk
    version: 0.10.1

  - package: Fleetio/dbt_segment
    version: 0.1.1

  - package: fivetran/salesforce_formula_utils
    version: [">=0.9.0", "<0.10.0"]

### What database are you using dbt with?

snowflake

### dbt Version

1.5

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-jamie** [comment]
hey there @RichardThRivera! thanks for taking the time to open this. 

i'm wondering if the issue here is around a field missing from the `SBQQ_QuoteLineGroup__c` table rather than `SBQQ__QuoteLine__c`, based on `failure_detail_1`?

**Comment by RichardThRivera** [comment]
Let me take a look - I'll reply to this ticket; Thanks Jamie!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @RichardThRivera were you able to take a look into this and if there is a field missing?
